import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    clerkId: v.string(),
    email: v.string(),
    name: v.string(),                // Real name
    pseudonym: v.string(),           // Anonymous name generated by app
    selfieUrl: v.optional(v.string()),
    idUrl: v.optional(v.string()),
    isApproved: v.boolean(),
    hasCompletedOnboarding: v.boolean(),
    createdAt: v.number(),
  })
  .index("byClerkId", ["clerkId"]),

  // Posts table
  posts: defineTable({
    userId: v.id("users"),      // Reference to user
    title: v.string(),
    content: v.string(),
    createdAt: v.number(),
  }),

  // Comments table
  comments: defineTable({
    postId: v.id("posts"),      // Reference to post
    userId: v.id("users"),      // Reference to user
    content: v.string(),
    createdAt: v.number(),
  }),

  // Admin actions table
  adminActions: defineTable({
    adminId: v.string(),        // Admin Clerk ID
    actionType: v.string(),     // 'approve_user', 'delete_post', etc.
    targetUserId: v.optional(v.id("users")),
    targetPostId: v.optional(v.id("posts")),
    targetCommentId: v.optional(v.id("comments")),
    timestamp: v.number(),
  }),

  // Optional payments table
  payments: defineTable({
    userId: v.id("users"),      // Reference to user
    paymentProvider: v.string(),// e.g., 'polar', 'stripe'
    paymentId: v.string(),
    status: v.string(),         // 'pending', 'completed', 'failed'
    amount: v.number(),
    createdAt: v.number(),
  }),
});
