import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

export const createUser = mutation({
  args: {
      clerkId: v.string(),
    email: v.string(),
    name: v.string(),                // Real name
    pseudonym: v.string(),           // Anonymous name generated by app
    selfieUrl: v.optional(v.string()),
    idUrl: v.optional(v.string()),
    isApproved: v.boolean(),
    hasCompletedOnboarding: v.boolean(),
    createdAt: v.number(),
  },
handler: async (ctx, args) => {
  const newUser = await ctx.db.insert("users", {
    clerkId: args.clerkId,
    email: args.email,
    name: args.name,
    pseudonym: args.pseudonym,                 
    hasCompletedOnboarding: args.hasCompletedOnboarding,
    selfieUrl: args.selfieUrl,
    idUrl: args.idUrl,
    isApproved: args.isApproved,
    createdAt: args.createdAt,
  });
  return newUser;
},

});

export const readUser = query({
  args: {
    clerkId: v.string(),
  },
  handler: async (ctx, args) => {
    try {
      const userInfo = await ctx.db
        .query("users")
        .filter((user) => {
          return user.eq(user.field("clerkId"), args.clerkId);
        })
        .first();   

      return userInfo;
    } catch (error) {
      throw new Error(`Failed to read user with clerkId: ${args.clerkId}`);
    }
  }
});

export const deleteUser = mutation({
  args: {
    clerkId: v.string(),
  },
  handler: async (ctx, args) => {
    try {
      // 1. Find the user document using the Clerk ID
      const userToDelete = await ctx.db
        .query("users")
        // Use the filter method to locate the document by clerkId
        .filter((q) => q.eq(q.field("clerkId"), args.clerkId))
        .first();

      // 2. Check if the user exists and delete them
      if (userToDelete) {
        // **IMPORTANT: Add Cascading Deletes Here**
        // e.g., Delete all posts or comments linked to userToDelete._id
        // await ctx.db.delete(post._id); 
        
        // 3. Delete the main user document
        await ctx.db.delete(userToDelete._id);
        
        console.log(`Successfully deleted user with Clerk ID: ${args.clerkId}`);
        return true; 
      }
      
      // If the user wasn't found, log a message but return true for the webhook 
      // to succeed (since the user is effectively "deleted" from Convex's perspective).
      console.log(`User with Clerk ID ${args.clerkId} not found in Convex.`);
      return true;
      
    } catch (error) {
      // Log the error for debugging purposes in your Convex dashboard or logs
      console.error(`Error deleting user with Clerk ID ${args.clerkId}:`, error);
      
      // Throwing the error will cause the mutation (and the calling webhook) to fail,
      // which often prompts the webhook provider (Clerk) to retry the operation later.
      throw new Error(`Failed to delete user in Convex: ${error}`);
    }
  },
});



